language: c
compiler:
  - clang
  - gcc
before_install:
  - if [ "$CC" = "clang" ]; then export CXX="clang++"; else export CXX="g++"; fi
  - if [ "$EXTRA_CFLAGS" = "-DUSE_VALGRIND" ]; then sudo add-apt-repository -y ppa:tmsz-kapela/valgrind-pmem; fi
  - sudo apt-get update -qq
  - sudo apt-get install -y libunwind7-dev autoconf devscripts pkg-config
  - if [ "$EXTRA_CFLAGS" = "-DUSE_VALGRIND" ]; then sudo apt-get install -y valgrind; fi
  - cp src/test/testconfig.sh.example src/test/testconfig.sh
  - perl -pi -e "s/^#PMEM_FS_DIR_FORCE_PMEM/PMEM_FS_DIR_FORCE_PMEM/" src/test/testconfig.sh
  - sudo mount -t tmpfs none /tmp -osize=4G
script:
  - if [ $MAKE_DPKG -eq 0 ]; then make check-license && make cstyle && make -j2 USE_LIBUNWIND=1 && make -j2 test USE_LIBUNWIND=1 && make check && make DESTDIR=/tmp source; fi
  - if [ $MAKE_DPKG -eq 1 ]; then make -j2 dpkg; fi
env:
  - NOTTY=1 MAKE_DPKG=0 EXTRA_CFLAGS=-DUSE_VALGRIND
  - NOTTY=1 MAKE_DPKG=0 EXTRA_CFLAGS=
  - NOTTY=1 MAKE_DPKG=1
