version: 1.0.{build}
os: Visual Studio 2015
platform: x64
configuration:
- Debug
- Release
matrix:
  fast_finish: true
before_build:
- ps: >-
    if ($env:CONFIGURATION -eq "Debug") {
        utils/CSTYLE.ps1
    }
build:
  project: src/NVML.sln
  parallel: true
  verbosity: minimal
test_script:
- ps: >-
    if ($env:CONFIGURATION -eq "Debug") {
        cd src/test
        cp testconfig.ps1.example testconfig.ps1
        ./RUNTESTS.ps1 -o 60s
    }
